// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZiifusmErZkTpj7jICBhGIjimnhiv9Hg',
    appId: '1:868719969585:web:833e31ab82e4afa8811c10',
    messagingSenderId: '868719969585',
    projectId: 'calm-vertex-387507',
    authDomain: 'calm-vertex-387507.firebaseapp.com',
    storageBucket: 'calm-vertex-387507.appspot.com',
    measurementId: 'G-Y0JYHEBHF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbcvMd23lkXI3FNWXsqEBTDEABtRqf2yg',
    appId: '1:868719969585:android:e952384b61cbbc6c811c10',
    messagingSenderId: '868719969585',
    projectId: 'calm-vertex-387507',
    storageBucket: 'calm-vertex-387507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJOuc2twD4VIEdzaeODuuuhcT6EPZ7ck',
    appId: '1:868719969585:ios:38e864610eec0256811c10',
    messagingSenderId: '868719969585',
    projectId: 'calm-vertex-387507',
    storageBucket: 'calm-vertex-387507.appspot.com',
    androidClientId: '868719969585-bpgpo2d95d6gh1ln0e9ebmmk7v0npcmm.apps.googleusercontent.com',
    iosClientId: '868719969585-e9n0i7hjrtk5q67e73cfuk0t7bpqivrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagaram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJOuc2twD4VIEdzaeODuuuhcT6EPZ7ck',
    appId: '1:868719969585:ios:cc86069dfb61ea3c811c10',
    messagingSenderId: '868719969585',
    projectId: 'calm-vertex-387507',
    storageBucket: 'calm-vertex-387507.appspot.com',
    androidClientId: '868719969585-bpgpo2d95d6gh1ln0e9ebmmk7v0npcmm.apps.googleusercontent.com',
    iosClientId: '868719969585-gk7du5feb830vf3c5tces014dhcu694f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagaram.RunnerTests',
  );
}
